---
- name: Search for Available Windows Updates
  win_updates:
    category_names: 
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
    state: searched
  register: available_updates
#      become: yes

- name: Display Available Updates
  debug:
    var: available_updates.updates

- name: Extract KB Numbers from Available Updates
  set_fact:
    kb_numbers: "{{ available_updates.updates | dict2items | map(attribute='value.kb') | list | flatten | join(',') }}"

- name: Display Extracted KB Numbers
  debug:
    var: kb_numbers

#- name: Install Updates with Extracted KB Numbers
#  win_updates:
#    category_names: SecurityUpdates
#    hotfix_id : "{{ kb_numbers }}"
#    state: installed
#  when: kb_numbers is defined and kb_numbers != ""
#      become: yes

- name: Install Updates with Extracted KB Numbers
  win_shell: |
    $kbNumbers = "{{ kb_numbers.split(',') | join('`,`') }}"
#    Install-WindowsUpdate -KBArticleID $kbNumbers -AcceptAll -AutoReboot
    foreach ($kb in $kbNumbers.split(',')) {
        $command = "wusa.exe /quiet /norestart /kb:$kb"
        Invoke-Expression -Command $command
    }
  when: kb_numbers is defined and kb_numbers != ""