---
- name: Patch Linux system
  remote_user: mohini
  hosts: all
  become: true
  ignore_errors: yes
  
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist  # This ensures that all packages are upgraded
        autoremove: yes
        autoclean: yes
