---
- name: Patch Linux system
  remote_user: ec2-user
  hosts: all
  become: true
  ignore_errors: yes
  
  tasks:
    - name: Update package lists
      yum:
        update_cache: yes

##    - name: Upgrade all packages
##      yum:
##        upgrade: dist  # This ensures that all packages are upgraded
##        autoremove: yes
##        autoclean: yes
