---
- name: Sample Windows Playbook
  hosts: all
  gather_facts: no  # Disable fact gathering for Windows hosts

  tasks:
    - name: Create a directory on Windows
      win_file:
        path: C:\ExampleDirectory\test
        state: directory
